@startuml Jualbeli

actor Pengguna
actor Admin
actor "Sistem Pembayaran" as PaymentSystem

usecase "Registrasi dan Login" as UC_Login
usecase "Cari Produk" as UC_Search
usecase "Lihat Detail Produk" as UC_ViewDetail
usecase "Tambah ke Keranjang" as UC_AddToCart
usecase "Checkout" as UC_Checkout
usecase "Pembayaran" as UC_Payment
usecase "Lacak Status Pesanan" as UC_TrackOrder
usecase "Notifikasi Pesanan" as UC_Notification
usecase "Manajemen Produk" as UC_ManageProduct
usecase "Manajemen Pesanan" as UC_ManageOrder

Pengguna --> UC_Login
Pengguna --> UC_Search
Pengguna --> UC_ViewDetail
Pengguna --> UC_AddToCart
Pengguna --> UC_Checkout
Pengguna --> UC_Payment
Pengguna --> UC_TrackOrder
Pengguna --> UC_Notification

Admin --> UC_ManageProduct
Admin --> UC_ManageOrder

UC_Checkout --> UC_Payment : "Pilih Metode Pembayaran"
UC_Payment --> PaymentSystem : "Koneksi ke Sistem Pembayaran"
UC_ManageOrder --> UC_Notification : "Kirim Notifikasi"

@enduml
