@startuml Pelanggan
start

:Buka Aplikasi;
:Admin Login;
if (Login Berhasil?) then (Ya)
    :Dashboard Admin;
    if (Ingin Kelola Data Pelanggan?) then (Ya)
        :Akses Modul Pelanggan;
        if (Tambah/Update/Hapus Pelanggan?) then (Ya)
            :Tambah/Edit/Hapus Data Pelanggan;
        endif
    endif
    if (Ingin Kelola Transaksi?) then (Ya)
        :Akses Modul Transaksi;
        if (Tambah/Update/Hapus Transaksi?) then (Ya)
            :Tambah/Edit/Hapus Data Transaksi;
        endif
    endif
    if (Ingin Melihat Laporan?) then (Ya)
        :Akses Laporan Pelanggan;
        :Lihat Analisis Pelanggan;
    endif
else (Tidak)
    :Tampilkan Pesan Error;
endif

:Pelanggan Login;
if (Login Berhasil?) then (Ya)
    :Dashboard Pelanggan;
    :Lihat Jadwal Kuliah/Pelangan;
else (Tidak)
    :Tampilkan Pesan Error;
endif

stop
@enduml
